# Configuraci칩n para Huawei Cloud App Engine
runtime: nodejs18

# Configuraci칩n de instancia
instance_class: F2
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

# Variables de entorno
env_variables:
  NODE_ENV: production
  PORT: 8080

# Archivos est치ticos
handlers:
  - url: /static
    static_dir: static
    secure: always
  
  - url: /.*
    script: auto
    secure: always

# Configuraci칩n de red
network:
  forwarded_ports:
    - 8080